### ISSUE TITLE
Allow Forced Disruption of Nodes after TTL (`disruptionTolerationDuration`)

### ISSUE THREAD

**Issue by levinedaniel** [kubernetes-sigs/karpenter#1047]
### Description

**What problem are you trying to solve?**
Currently we are advising teams that submit workloads to our cluster to use the 'do-not-drift' label within pods to allow for ML workloads to finish uninterrupted. Some of these workloads can stay indefinitely on the cluster. As cluster admins, It would be ideal if we could force remove nodes that pass a certain threshold of time past the time the nodeclaim is drifted. The longer the node stays out, we more chance we can accumulate vulnerabilities from the infrastructure.

We can implement someone similar i.e. deploying a cronjob that takes the action specified above, however I believe it would make sense to have this functionality native to Karpenter as it is something that any cluster admin could run into.

I would be interested in working on this issue should the idea gets approved.

**How important is this feature to you?**
This feature would result in a decrease of the SRE team it takes to maintain clusters. As such, it is fairly important to use before we wide-spread adopt karpenter.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Could you leverage [these controls](https://github.com/kubernetes-sigs/karpenter/blob/59c79ee552198a78e4f7133eebba21c0426a6631/designs/disruption-controls-by-reason.md#approach-a-extending-the-budget-api-to-specify-a-reason) to have windows where you allow drift, and windows where you dont? Every weekend for example you allow drift and during weekdays you dont?

**Comment by levinedaniel** [comment]
@Bryce-Soghigian the primary issue with just using disruption controls is that we would ideally like to start the timer as the workload comes in or the node is drifted to give our downstream users an expectation for how long they will have for their deployments. 

Given this scenario:
- User deploys workload Thursday 
- We update amis Friday

we wouldn’t want their nodes to re-provision that soon if we want to give them an allocation of a week for their model to run. 

We could delay updating the ami but in our situation we would like to just specify ami tags and let Ami’s stream in as they are created. 

If we specify disruption gates to just re-provision on weekends we also risk leaving instances running for the better part of a week when they are not in use.

**Comment by Bryce-Soghigian** [comment]
> start the timer as the workload comes in or the node is drifted to give our downstream users an expectation for how long they will have for their deployments.

Could you use [node expiration](https://karpenter.sh/docs/concepts/disruption/#automated-methods) then? Or rather than `do-not-drift`, would [min age](https://github.com/kubernetes-sigs/karpenter/issues/1030) work for this usecase? 

If you set minAge on the nodeclaim, it will not be disrupted until after the node is at least X Days old.

**Comment by levinedaniel** [comment]
@Bryce-Soghigian min age might get us closer. The issue with min age is that even if workloads drop off early, we would be subjected to the min age set, leading to unnecessary costs.

**Comment by njtran** [comment]
Do you have a problem that you have nodes are remaining long after your expiration time? Or are you expecting nodes to be living no longer than 30 days on the dot?

**Comment by sftim** [comment]
One way to address this, maybe: blue/green node pools. Perhaps we - Kubernetes - can provide some sample code for switching to the other node pool every _n_ days.

**Comment by njtran** [comment]
This is something that @jonathan-innis and I were discussing. Currently, we don't taint nodes if they're drifted or expired, meaning that you have a chance for do-not-disrupt job pods to reschedule onto the same node when they complete. This essentially means that you have a chance for nodes to be drifted or expired indefinitely.

We're thinking of solving this by adding a way to configure how long after a node is expired or drifted that it is forcibly drained and deleted. You could solve this by ensuring that nodes are just always enqueued for disruption, rather than considering the do-not-disrupt and rely on a [drain timeout](https://github.com/kubernetes-sigs/karpenter/issues/743) to forcibly drain it too. But I think these diverge in two use-cases: 

1. Users who want graceful eviction and draining once a node has been expired/drifted, but only wants a forceful application disruption after a period of time
2. Users who want to make sure that nodes are no longer in the cluster by a period of time and do not care about application disruptions.

**Comment by levinedaniel** [comment]
Yes fully agree. For our use case, we would definitely prefer the former. We could find ourselves in a situation where an application exits early and we want to clean up the node immediately after the last pod exits. 

@njtran I saw you removed the needs triage label, would you and/or @jonathan-innis support adding this to the project?

**Comment by jonathan-innis** [comment]
cc: @akestner @ellistarn

**Comment by jonathan-innis** [comment]
> there are bad PDB's set and that would not allow eviction of the pod once the pod lands on the node and have a TTL to expire the node will help us deal with these kinds of scenarios

For the case around PDBs, does [Unhealthy Pod Eviction Policy](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#unhealthy-pod-eviction-policy) help you at all? At the very least, you can tell Kubernetes that you are okay to evict pods that have never started even if doing so would break the PDB. Note though that this is only in beta starting on 1.27.

I'm +1 on supporting a cluster admin-level configuration to force terminate pods through disruption. I think having this + #752 + #743 gives both application owners and cluster admins _a lot_ of flexibility on how much they tolerate disruption.

**Comment by wmgroot** [comment]
We have the same issue and we're currently running a patch that outright disables Karpenter removing nodes with non-evictable and non-disruptible pods from the disruption candidate filtering process. 

This patch combined with my `terminationGracePeriod` PR gives cluster administrators the ability to specify a hard limit for node lifetime after Karpenter decides that a node should be disrupted. Pods can still prevent disruption of the node via PDBs, preStop hooks, and the `do-not-disrupt` annotation, but only up to the `terminationGracePeriod` of the NodeClaim. It also implements a `do-not-consolidate` annotation that blocks disruption via consolidation methods, but not other methods like drift.

https://github.com/wmgroot/karpenter/pull/1/files
https://github.com/kubernetes-sigs/karpenter/pull/916

**Comment by levinedaniel** [comment]
@jonathan-innis do you need an implementer for this? I can take a first pass unless someone on the team wants to take it.

**Comment by wmgroot** [comment]
To be specific, would you be looking to implement a solution for allowing disruption to occur on nodes with non-evictable or non-disruptible pods? I believe my `terminationGracePeriod` PR will already provide the capability for cluster admins to restrict how long a pod can keep running when node disruption needs to occur (via drift, expiration time, etc).

**Comment by levinedaniel** [comment]
@wmgroot apologies did not read your comment closely enough. #916 looks like it would solve the issue here!

**Comment by wmgroot** [comment]
Having also thought about this issue more, I think what you were envisioning would be an effective "disruption delay" where the node would be:

1. A node becomes considered for disruption.
2. The node is tainted to prevent new scheduling.
3. Actual disruption is delayed by X amount of time (configureable on the NodeClaim via template).
4. Pods on the node are granted X amount of time to continue their work, but are unaware that the node will soon be disrupted.
5. Normal disruption process is followed after the disruption delay expires.

I think this has some tradeoffs and limitations, but can effectively be accomplished with `terminationGracePeriod` with more flexibility by configuring preStop hooks on the pods that need to delay disruption of the node. The main issue I see with what I've described above is that the node's disruption is *always* delayed by X amount of time, whereas with `terminationGracePeriod` the node can proceed with termination as soon as the pods have terminated.

**Comment by levinedaniel** [comment]
@wmgroot I absolutely agree, it makes a lot more sense to terminate early if the pods have already been terminated

**Comment by vinayan3** [comment]
We've been looking for a solution to this problem where there are some Pods that hold up nodes indefinitely. 

Our usecase is that we upgrade the cluster which causes the nodes to be in drifted state. Since the Nodes are running pods with the annotation for do not evict the nodes around in-definitely. Some of the pods finish but often before all the pods are gone some other Job pod will get onto the node. 

The only intervention we have been able to do is to manually cordon all of these nodes and then wait for them to drain out. 

For our usecase it'd be great if Karpenter tainted or cordoned a node that needs to go away. Then after a TTL , set by cluster admins, Karpenter drains the node and deletes it.

**Comment by jmdeal** [comment]
I'm currently working on an RFC to address https://github.com/kubernetes-sigs/karpenter/issues/622, I believe it should address your issue with `do-not-disrupt` pods continuously scheduling preventing disruption @vinayan3. I'm also taking a stab at this issue as part of that since they're pretty closely related.

My initial thought was we add a candidate TTL, this would define the maximum duration a node may remain a disruption candidate before it is considered terminable. Once that TTL has been met, a node will be considered terminable regardless of blocking PDBs or `do-not-disrupt` pods, but it could be considered terminable earlier. This is similar to what @wmgroot described in this [comment](https://github.com/kubernetes-sigs/karpenter/issues/1047#issuecomment-1992933686) but would solve the constant delay problem. I think this works well, but don't love needing two fields to control termination timeouts (terminationGracePeriod and candidateTTL).

Discussed offline with @jonathan-innis for a bit and we think just using `terminationGracePeriod` could still be a good solution, with some slight modifications to our drain logic. We would immediately consider the node to be terminable if the corresponding nodeclaim has a terminationGracePeriod set and the termination flow would begin when disruption budgets allow. We'd treat `do-not-disrupt` pods as though they had a blocking PDB and they would be deleted via the work in the terminationGracePeriod PR. 

I prefer the second approach more from an API standpoint, but it does have some limitations compared to the first. With the latter, `do-not-disrupt` pods wouldn't be evicted until the end of the terminationGracePeriod. If you wanted to give 15 minutes, for example, for `do-not-disrupt` pods to leave the node naturally before deleting it you would be left with a partially drained node for those 15 minutes. With the separate fields you could have a 15 minute candidate TTL and a shorter terminationGracePeriod, increasing average cluster utilization and decreasing overall cost. Definitely curious to know what others think of those tradeoffs.

**Comment by vinayan3** [comment]
> Discussed offline with @jonathan-innis for a bit and we think just using `terminationGracePeriod` could still be a good solution, with some slight modifications to our drain logic. We would immediately consider the node to be terminable if the corresponding nodeclaim has a terminationGracePeriod set and the termination flow would begin when disruption budgets allow. We'd treat `do-not-disrupt` pods as though they had a blocking PDB and they would be deleted via the work in the terminationGracePeriod PR.


Does the adjustment to the drain logic include cordoning the nodes? For our clusters with CronJobs and Pods controlled by argo workflows (basically it creates a Pod for a Batch Job) cordoning will ensure no new Job pods are scheduled onto the node.

**Comment by wmgroot** [comment]
With my understanding of @jmdeal 's proposal, you'd be able to set the `candidateTTL` for each NodeClaim to `0s`, which would let the standard drain and `terminationGracePeriod` logic start immediately. The drain process does taint the node to prevent further scheduling.

**Comment by jmdeal** [comment]
Cordoning the nodes is part of the RFC I'm currently working on and I think can be considered separately from this issue. The gist is nodes would be tainted as soon as they are expired or drifted, the RFC is basically just looking at the different options for the taint effect (`NoSchedule`, `PreferNoSchedule`, something dynamic, user configurable, etc). 

@wmgroot is right that without any update to today's logic, my first proposal would work for you if you set `candidateTTL` to `0s` and configured your `terminationGracePeriod` accordingly. The second proposal would work the same way **if** `terminationGracePeriod` is configured for the node. 

The intention for the first proposal is that it would be combined with the updated tainting behavior though. Let's say candidate nodes (expired / drifted) are tainted with `karpenter.sh/disruption=candidate:NoSchedule`. This would prevent any new pods from scheduling to the node. Once there are no more blocking pods (blocking PDBs, `do-not-disrupt`) or once the `candidateTTL` has expired the node would be considered terminable and the `terminationGracePeriod` logic would begin. This level of granularity might be overkill though, hence the second proposal which just uses `terminationGracePeriod`.

**Comment by jmdeal** [comment]
Thought on this some more, realistically I see extending the `terminationGracePeriod` feature as the correct first step. This is the second option I mentioned previously, remove the filter for nodes with `do-not-disturb` pods or blocking PDBs if the corresponding nodeclaim has a terminationGracePeriod set. This only has a couple of drawbacks:
- Doesn't support users who want Karpenter's current candidacy logic (wait for no blocking PDBs or `do-not-disrupt` pods **and** want to set a `terminationGracePeriod`
- Doesn't support a period for `do-not-disrupt` pods to leave on their own before beginning the drain
  - If we wanted to support this it would need to be driven through `terminationGracePeriod`and we'd basically want to treat pods with the `do-not-disrupt` annotation as though they have a permanently blocked PDB. They would then be deleted by the `terminationGracePeriod` feature at `gracePeriodExpirationTime - terminationGracePeriodSeconds (pod)`. This would still begin the drain immediately, lowering cluster utilization and raising costs compared to a pre-drain period.

Realistically though, I don't think there's enough indication that either of these two points are important to users currently. @wmgroot do you have any thoughts on extending your PR to incorporate this? It sounds like it's more or less what you're already doing with your [patch](https://github.com/kubernetes-sigs/karpenter/issues/1047#issuecomment-1990672033) along with potentially considering `do-not-disturb`pods blocking for the duration of the `terminationGracePeriod`.

**Comment by wmgroot** [comment]
What you're describing would meet my use case. I don't think it should be incorporated into the current PR since it's close to finalized and I'd like to avoid any delays in having that piece merged. I don't think it would be difficult to follow up with an addon for this issue.

The one case that is sticky for us is supporting good termination practices for job pods that lose progress when interrupted. I'm currently exploring smarter preStop options that can identify the source of pod termination in order to decide if allowing or delaying the termination is preferred option.

I'm not sure if tying this logic to the terminationGracePeriod field or if supporting a new field for this behavior would be preferred.

One additional downside to the approach you've described is that the disruption candidate logic would need to consider every nodeclaim in addition to each node, which is more action on the K8s API. Alternatively, the nodeclaim could need to mark each node (probably an annotation) to not be excluded for do-not-disrupt or non-evictable pods.

**Comment by jzuhusky** [comment]
This problem definitely sounds like something we're experiencing as well. We have nodes that have expired or drifted but won't be de-provisioned b/c of a single blocking PDB. Ideally we wouldn't like to manually fix these issues on our multi-tenant clusters - our SLA with our users is that nodes are cycled in and out a lot, and if your deployments have broken pods, that's on you. 

@wmgroot It looks like this PR: https://github.com/kubernetes-sigs/karpenter/pull/916 solves the issue - although I'm unsure. It sounds like some of the conversation about indicates that this probably won't solve our issue. 

Does this feature only force kill nodes that are already cordoned and being drained? Or would this address the issue I've mentioned I've seen above where PDBs block deprovisioning therefore nodes won't be cordoned and drained and will just continue to run indefinitely (even with workloads that aren't associated with the offending PDB). Thanks

**Comment by wmgroot** [comment]
My PR is one piece needed to solve the problem, but not a complete solution on its own. I've been pretty busy with work fires the past week, but I'm eager to get some work done this week on implementing the other piece that you're looking for as a followup.

**Comment by wmgroot** [comment]
As a heads up for anyone watching this the `terminationGracePeriod` PR is being updated to also handle disruption for non-evictable and do-not-disrupt pods: https://github.com/kubernetes-sigs/karpenter/pull/916

**Comment by levinedaniel** [comment]
This issue can likely be closed with the completion of #916. Thank you @wmgroot!
