### ISSUE TITLE
a nodeclaim not being registered results in other node claims not being created from other node pools

### ISSUE THREAD

**Issue by tvonhacht-apple** [kubernetes-sigs/karpenter#1120]
### Description

**Observed Behavior**:

When a nodeclaim is failing for a specific nodepool, other nodeclaims are not scheduled unless that nodeclaim comes up or is deleted.

**Expected Behavior**:

nodeclaims from different nodepools should be independent from being scheduled.

**Reproduction Steps** (Please include YAML):
build your own binary that creates a fake tag that is starts with a `-`. schedule multiple pods on different nodepools. watch nodeclaim being created for first nodepool, do not see how other nodeclaim for different nodepool gets scheduled until nodeclaim is deleted.

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tvonhacht-apple** [comment]
interested in working on the issue

**Comment by engedaam** [comment]
@tvonhacht-apple Why is the NodeClaim fail launch the underlaying node? Also, did any pending pods that were created after the NodeClaim that were able to be scheduled to the node Karpenter expected be register?

**Comment by tvonhacht-apple** [comment]
The behavior we found, that it was not related NodePools or EC2NodeClasses. It would just overall not bring up any new nodes, until node correctly register with Karpenter

**Comment by jonathan-innis** [comment]
> When a nodeclaim is failing for a specific nodepool, other nodeclaims are not scheduled unless that nodeclaim comes up or is deleted

This is interesting. So...the reason that we currently don't allow ourselves to launch when we get a failure is because we don't know what that capacity is going to look like. Scheduling without knowing what that capacity could look like means that we could make the wrong decision when trying to reschedule without this capacity resolving and the prospect of unblocking here is somewhat tricky. 

One interesting idea here is still considering that NodeClaim capacity as capacity that can be scheduled against and continue to model pods against that capacity in a new scheduling round rather than completely stopping simulating. There's a few considerations that we'd have to make here:
1. NodeClaims could launch while we are simulating -- the sizing of the node that actually gets launched is going to affect the scheduling decision that we just went with, so we probably have to throw it out, so we waste a bit more work
2. NodeClaims that were already created should continue to be able to be constrained if they haven't launched. This allows the scheduling simulation to update the existing NodeClaims with additional constraints after they have already been created -- so it can make an initial decision, but then edit this decision. This also has the potential to have race conditions because it's possible for the NodeClaim to launch while we are editing it -- in this case potentially getting a smaller instance type than what we assumed from the previous scheduling simulation.

Overall, I think our position is basically: NodeClaims failing in this way should generally be cause by misconfigurations in EC2NodeClass so over-indexing for trying to solve this case may not be worth the effort AND the effort of trying to solve for this and avoid all of pitfalls and potential race conditions is going to take a good bit of thought, is going to make the code more complicated, and is going to be more difficult to test.

**Comment by engedaam** [comment]
@tvonhacht-apple Are you seeing pending pods in the cluster that will not fit on NodeClaims created by Karpenter? Are seeing that pods that should be scheduled on NodePool #A are pending until NodeClaims owned by NodePool #B are registered? Also are you able to share any logs during this event?
