### ISSUE TITLE
Upgrading NodeClass via custom Helm Chart fails

### ISSUE THREAD

**Issue by Phylu** [kubernetes-sigs/karpenter#1282]
We are installing the `karpenter-crd` helm chart. Then we have our own internally managed help chart that makes use of the CRDs to define an EC2NodeClass and multiple NodePools. When we do a change on our configuration, e.g. adding a tag to the EC2NodeClass, I'd expect this to be a minor change that can be easily applied.

However, when I apply the updated helm chart, helm tries to delete the EC2NodeClass and then recreate it with its new configuration. This fails as there are nodes currently running with that class and therefore the karpenter finalizer (luckily) intervenes. The EC2NodeClass with the updated configuration can't be created and I get the error message `object is being deleted: ec2nodeclasses.karpenter.k8s.aws "default" already exists`.

How is it possible that helm will just patch the existing EC2NodeClass instead of trying to recreate it?

**Comment by fmuyassarov** [comment]
> The EC2NodeClass with the updated configuration can't be created and I get the error message `object is being deleted: > ec2nodeclasses.karpenter.k8s.aws "default" already exists`.
> 
I think this is expected behavior, because as you said there are nodes owned by the previous `EC2NodeClass`. 

> How is it possible that helm will just patch the existing EC2NodeClass instead of trying to recreate it?

It is more about the behavior of  Kubernetes than the Helm, because it is Kubernetes who decides weather the object needs to be re-created or can be patched in-place.  Basically, if you are modifying the fields that can be easily mutated (for example labels, annotations or things of that sort) then Kubernetes won't re-create the object and instead patch the it in-place. But for example, if you try to modify let's say the image of your Pod (which is immutable field) then it needs to be re-created with the new image.

**Comment by engedaam** [comment]
@Phylu Apologize on the late response from the team. Would you be willing to close out this issue in favor for https://github.com/aws/karpenter-provider-aws/issues/6249

**Comment by Phylu** [comment]
@engedaam Sure.
