### ISSUE TITLE
Karpenter on AWS without EKS

### ISSUE THREAD

**Issue by izaakschroeder** [kubernetes-sigs/karpenter#1376]
### Description

**What problem are you trying to solve?**

Running `karpenter` on an K8S cluster within AWS that is **NOT** managed by EKS.

Currently it looks like calls to `eks` are relatively limited and in some cases even bypassed when certain configurations are present (e.g. URL to API server). If it were possible to manually specify configuration for the other parts that invoke `eks` then this feature should be possible to build. From my very cursory reading into the code, it seems like the CIDR range is the primary culprit here?

**How important is this feature to you?**

Depending on the organization can be anywhere from nice to have to required depending on what kind of overrides are needed for the control plane and if it's possible to achieve them within EKS.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
^^ This should be filed against the AWS provider. That being said, there shouldn't be anything stopping you from running on AWS directly. We only query cluster CIDR via `eks:DescribeCluster` when the eks optimized AL2023 AMI family is being used. There shouldn't be a reason to use this AMI in a non-EKS environment. I'm going to close the issue here, feel free to open another issue in the AWS repo if you have further questions.

/close

**Comment by izaakschroeder** [comment]
Ah great! Sorry for my ignorance I'll have a look over there; thanks again for the fast reply 😄
