### ISSUE TITLE
Understading karpenter's default vmMemoryOverheadPercent value

### ISSUE THREAD

**Issue by Balraj06** [kubernetes-sigs/karpenter#1542]
Hi. Im trying to unserstand the reason why vmMemoryOverheadPercent value is 0.075 by default. Any specific reasons?

**Comment by njtran** [comment]
This is a value that we picked, looking at instance types (across AWS) and found that 0.075 was a percentage that minimized the error for all instance type sizes. Note that this is just an estimate, and can be overshot or undershot, and should be adjusted based on the instance type sizes you're using.

**Comment by jukie** [comment]
@njtran For the aws provider could we generate for all known instance types as was seemingly started here? https://github.com/aws/karpenter-provider-aws/blob/33450d8f82ded870ce65fbde3cec14dbb2c04f50/pkg/providers/instancetype/zz_generated.memory_overhead.go

Then for unknown instance types `vmMemoryOverheadPercent` could be used.

**Comment by Balraj06** [comment]
@njtran  what is the error that you are trying to avoid with this value as you mentioned "minimized the error for all instance type sizes"

**Comment by njtran** [comment]
By error I meant mean error. The problem here is basically is what value of `vmMemoryOverheadPercent` creates a line of best fit that minimizes your mean error. Ultimately this comes down to what you expect the general size of your OS for the images that run on your machines, and how do they differ across the instance types that you run? We've done simulations that in the past might have shown `0.075` as the best default for some of the basic/default setups that we saw, but this can change over time as new instances/images are released, and ultimately it's up to you to help inform Karpenter what the best estimation is here. 

One thing we're considering doing as part of post-v1 is to cache the result of created nodes to affect the future state of what overhead actually calculates to. For instance, this means that Karpenter would try to calculate a NodeClaim, estimating an end-result of allocatable and launch a node. The node could join the cluster later, with either more or less allocatable, and Karpenter would use those results to inform future decisions for nodeclaims that have the same instance types, images, etc.
