### ISSUE TITLE
Consider K8s version when drift handling for amiSelectorTerms 

### ISSUE THREAD

**Issue by alex067** [kubernetes-sigs/karpenter#1655]
### Description

**What problem are you trying to solve?**
Karpenter provides automatic drift detection when an updated AMI is released. However this only works if you use amiFamily / a very liberal and flexible ami selector. 

For those who need to use amiSelectorTerms to specify specific AMI Ids, drift detection doesnt seem to consider the k8s version. This was tested on karpenter 0.34, where Karpenter drifted all nodes even though the AMI was for the next k8s version.

**How important is this feature to you?**
This is critical.

We cannot rely on loose ami selectors or liberally use amiFamily, as we do not want our nodes to constantly get updated based on recent AMI releases. We would like to control the AMI update process, whilst also having the ability when performing cluster upgrades, for Karpenter to help us with drift.

The preferred workflow would be:
1. Update the amiSelectorTerms with the next AMI Id for the next k8s version
2. Apply but no drift is performed as Karpenter acknowledges current cluster version
3. Update cluster version to next
4. Karpenter acknowledges new cluster version, performs drift as the next AMI ID in the selectorTerm qualifies

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Do you mind re-opening this in [aws/karpenter-provider-aws](https://www.github.com/aws/karpenter-provider-aws)? AMI drift is implemented there, not in this repo.

A high level question though, is there any reason you need to update your amiSelectorTerms before upgrading your k8s version? Could you address by updating your order of operations such that 1 occurs after 3? Happy to discuss more in the other repo.

**Comment by jonathan-innis** [comment]
There's a similar feature request here: https://github.com/aws/karpenter-provider-aws/issues/4769. @alex067 I suspect that this is effectively what you are asking -- where you could do something like define the discovered K8s version as a tag, part of the AMI name, or part of an SSM path and Karpenter would inject that at runtime. 

In this case, if you had tagged the new AMI in a specific way, you could select against AMIs with `k8s-version: $K8S_VERSION`. Given that issue is opened in the AWS repo, I'm going to close this one out.

Feel free to add your use-case to that issue if you don't feel that it's covered in the existing one.
