### ISSUE TITLE
Support 'singleProcessOOMKill' kubelet config flag?

### ISSUE THREAD

**Issue by MrFishFinger** [kubernetes-sigs/karpenter#1804]
### Description

**What problem are you trying to solve?**

In https://github.com/kubernetes/kubernetes/pull/126096 the kubelet config flag `singleProcessOOMKill` was added to allow disabling the "cgroup aware OOM Killer". Is there a way to set this flag from karpenter? in particular for a node running Bottlerocket?

***

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
We've moved our kubeletconfiguration into cloudprovider-specific NodeClasses to allow each CloudProvider to decide which configuration that they want to support. I'd recommend opening an issue in the cloudprovider-specific repo so that folks from that provider can chime in to what their support is for certain features/settings.

**Comment by mprice3-etr** [comment]
EC2NodeClass

spec
  userData: |
    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      kubelet:
        config:
          singleProcessOOMKill: true
