### ISSUE TITLE
Remove `apis.FieldError` in favor go error interface 

### ISSUE THREAD

**Issue by engedaam** [kubernetes-sigs/karpenter#620]
### Description

**What problem are you trying to solve?**
- In an effort to remove direct reliance on `knative.dev/pkg` https://github.com/aws/karpenter-core/issues/332
- Remove all instances of `apis.FieldError` to rely on the go error interface completely
- This would be for v1beta1 APIs (`Nodepools` and `NodeClaims`) 
- https://github.com/aws/karpenter-core/blob/main/pkg/apis/v1beta1/nodepool_validation.go
- https://github.com/aws/karpenter-core/blob/main/pkg/apis/v1beta1/nodeclaim_validation.go

**How important is this feature to you?**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bharadwajshivam28** [comment]
Hello @engedaam  i want to work on this issue sir

**Comment by Bharadwajshivam28** [comment]
What I understand is that our goal is to-

1) Remove the `knative.dev/pkg` usage
2) Replacing the usage of `apis.FieldError` with interface

**Comment by jonathan-innis** [comment]
I'm questioning how much we want to do this actually because, as this is developing, I'm thinking that we are most likely going to end up keeping the webhook with knative but we will just create a separate module for the webhook. With that in mind, I think that we can probably punt on this for now until we get more clarity into how that webhook separation is going to work.
