### ISSUE TITLE
Support `kubeletConfiguration.failOnSwap` and `kubeletConfiguration.memorySwap` in `Provisioner` spec

### ISSUE THREAD

**Issue by OrBin** [kubernetes-sigs/karpenter#663]
### Description

**What problem are you trying to solve?** Set `failOnSwap=false` and `memorySwap=...` on kubelet configuration.

**How important is this feature to you?** It's necessary for us to be able to use swap memory on Karpenter-controlled nodes.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by OrBin** [comment]
Yes, that's exactly what I'm asking to configure.
I'm currently using Karpenter v0.27, does it mean I have to upgrade to v0.32 to be able to use the the v1beta1 APIs?

**Comment by jonathan-innis** [comment]
Going to close this one in favor of https://github.com/aws/karpenter-provider-aws/issues/5833. I think Cloud Providers will be opening specific issues for adding support for additional kubelet config fields since there is a plan to shift the location of this stanza at v1 (see https://github.com/kubernetes-sigs/karpenter/issues/758#issuecomment-1971592904)
