### ISSUE TITLE
Unschedulable Pod Metric

### ISSUE THREAD

**Issue by sidewinder12s** [kubernetes-sigs/karpenter#705]
### Tell us about your request

We used this metric with the cluster_autoscaler `cluster_autoscaler_unschedulable_pods_count`. 

Would it be possible to have Karpenter expose a similar metric?

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

How to alert when Karpenter is unable to scale out

### Are you currently working around this issue?

Looking at Kubernetes Scheduler metric `scheduler_pending_pods`, however if you have multiple schedulers this gets more complicated. 

EKS also does not expose metrics from the Kubernetes Scheduler. 

### Additional Context

We might have been abusing this metric a bit as the OSS Autoscaler would also observe entire cluster state. 

We have 2 Autoscalers running (CAS and an Internal autoscaler), so we were somewhat overloading on this metric since CAS still took a whole cluster view even if it wasn't scaling most of our nodes. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Horiodino** [comment]
Hii, how about I work on it!

**Comment by Bryce-Soghigian** [comment]
@njtran many users with large clusters probably will want to avoid scraping the high cardinality series of kube_pod*

all the kube_pod* are rather high cardinality metrics and aren't as scalable as the CAS metric imo.

**Comment by jonathan-innis** [comment]
@Horiodino Assigned!

**Comment by jonathan-innis** [comment]
Seems like this one might be difficult for the same reason that #686 is difficult. The second you get multiple NodePools into the mix, we now have to figure out which NodePool we think you _intended_ to schedule the pod to; otherwise, we might fire multiple metrics, one for each NodePool. There's basically a 1-1 reasoning between why the pod wouldn't have scheduled to a NodePool with Karpenter. Maybe this means what we are really looking for here is a pod metric with a nodepool label and pod label that tells us the reason why the pod didn't schedule against each NodePool.

I still haven't looked into how complex that might be to orchestrate or how much cardinality that would add to pod metrics that already have pretty high cardinality to begin with.

**Comment by njtran** [comment]
This sounds reasonable @sidewinder12s. It could be simply added here: https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/controllers/provisioning/scheduling/scheduler.go#L193-L196

**Comment by jonathan-innis** [comment]
> Actually using the metric you'd likely use a rate or duration of elevated count to indicate Karpenter is unable to process some pod

+1, on board with this. Textbook overthinking on my part. A basic gauge that gets changed on each provisioning loop sounds completely reasonable.

**Comment by omerap12** [comment]
Hey @jonathan-innis, could you take a look when you get a chance (https://github.com/kubernetes-sigs/karpenter/pull/1778) ? If everything looks good, I’ll go ahead and finalize the PR. (Still deciding whether to create a unit tests file.)
