### ISSUE TITLE
NodeName label in Karpenter metrics

### ISSUE THREAD

**Issue by karadia10** [kubernetes-sigs/karpenter#707]
### Tell us about your request

Adding Nodename label in karpenter Metrics for the node actions performed

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Karpenter exposes multiple metrics for nodes listed in [here](https://karpenter.sh/v0.27.2/concepts/metrics/) 
Although they do give insights on Node actions performed like Provision, de-provision, interruption etc but when we receive the metrics it does not provide insights on which node is getting affected by the action, it just provides karpenter pod name on which the action was taken and it's IP

### Are you currently working around this issue?

I am trying to learn on operators but it will take me some time to understand the structure

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
we should avoid adding a node label if we can because node level cardinality can explode quickly. Karpenter has done a good job with the node metrics making them counters or gauges with low label value pair cardinality.

 At scale this becomes a nightmare if you have Metric series with the node label, then those nodes get churned, and the cluster sees an explosion of cardinality. For a system like karpenter that consolidates frequently this is especially concerning. 
 
[Here](https://kubernetes.slack.com/archives/C09R1LV8S/p1705020536810739) is one real example of customer pain, and they were only scaling down and up 40-60 nodes at a time. For high scale k8s clusters that scale to 1000 nodes+ then scale down, this becomes a nightmare to manage.
