### ISSUE TITLE
Support for node problem detector

### ISSUE THREAD

**Issue by runningman84** [kubernetes-sigs/karpenter#738]
### Tell us about your request

We used to run [node problem detector ](https://github.com/kubernetes/node-problem-detector) in combination with drainio and cluster-autoscaler. Once a problem was detected drainio/cluster-autoscaler removed the node.

Dranio is not really maintained anymore and cluster-autoscaler is replaced by karpenter in our usecase.

It would be great if karpenter would also look for node conditions like
* KernelDeadlock
* ReadonlyFilesystem
* FrequentKubeletRestart
* FrequentDockerRestart
* FrequentContainerdRestart

and drain the corresponding node. Maybe this list could be configured in the karpenter setup...

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

We would like to reduce complexity, because karpenter manages nodes anyway it seems to make sense to also include this feature.

### Are you currently working around this issue?

Trying to switch to the DataDog drainio fork.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by uje-m** [comment]
Interesting proposal

**Comment by Bryce-Soghigian** [comment]
AKS Also uses node problem detector to detect events and fire auto-healing actions on the nodes. We use these scheduled events to cordon and drain nodes via node auto drain as part of the node auto healing framework. This is the reason we didn't implement an interupt controller in the aks provider because we already have a component that will respond to interurption events. 

See: 
 - https://learn.microsoft.com/en-us/azure/aks/node-problem-detector#events
 - https://learn.microsoft.com/en-us/azure/aks/node-auto-repair#node-auto-drain
 
 Also related: https://github.com/kubernetes-sigs/karpenter/issues/750

**Comment by jonathan-innis** [comment]
This definitely has some overlap with #750

**Comment by sherifabdlnaby** [comment]
Since Draino is deprecated; It make total sense for Karpenter to react to Problem API.
