### ISSUE TITLE
support drain timeout

### ISSUE THREAD

**Issue by grosser** [kubernetes-sigs/karpenter#743]
**Tell us about your request**
Sometimes nodes get stuck when a pod could not be drained, so we have to alert ourselves and then manually kill it, which is not ideal.

It would be nice to set an optional `drainTimeout` so we can ensure nodes always die after x hours/days.

**Are you currently working around this issue?**
Helper pod that kills pods on stuck nodes so they finish draining.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by wmgroot** [comment]
Just for reference, this is the field that supports this behavior in ClusterAPI.
```
$ kubectl explain machinedeployment.spec.template.spec.nodeDrainTimeout
KIND:     MachineDeployment
VERSION:  cluster.x-k8s.io/v1beta1

FIELD:    nodeDrainTimeout <string>

DESCRIPTION:
     NodeDrainTimeout is the total amount of time that the controller will spend
     on draining a node. The default value is 0, meaning that the node can be
     drained without any time limitations. NOTE: NodeDrainTimeout is different
     from `kubectl drain --timeout`
```

In our case, we set this value to `24h` in all clusters, production or otherwise. We make it clear to our users that they must tolerate graceful disruption of their pods, and to alert themselves if their pods are in an unhealthy state for a long period of time in production. This allows us to ensure we can keep up to date with security patches across all of our clusters.

We've discussed lowering the value from 24h to something much shorter once we have a better story for automated traffic failover between our clusters.

**Comment by wmgroot** [comment]
Should support for volume detach timeouts be opened as another issue? We use EBS CSI and find that some volumes refuse to detach due to timeouts that aren't handled well by the EBS CSI controller. We've opened several issues there, but these problems still occur after years of using EBS CSI. This blocks removal of nodes and can greatly delay the process of updating nodes in a cluster if left to manual intervention.
```
$ kubectl explain machinedeployment.spec.template.spec.nodeVolumeDetachTimeout --context mgmt-use2
KIND:     MachineDeployment
VERSION:  cluster.x-k8s.io/v1beta1

FIELD:    nodeVolumeDetachTimeout <string>

DESCRIPTION:
     NodeVolumeDetachTimeout is the total amount of time that the controller
     will spend on waiting for all volumes to be detached. The default value is
     0, meaning that the volumes can be detached without any time limitations.
```

**Comment by garvinp-stripe** [comment]
I think in general there is a need/ desire for more control over how nodes shut down happens from cluster operators from timeouts and how drain happens. 

Wondering if we should prioritize https://github.com/kubernetes-sigs/karpenter/issues/740 to expand how node termination happens and exposing more control for users?

**Comment by ellistarn** [comment]
Supportive of a node drain timeout proposal. Anyone want to take this on?

**Comment by wmgroot** [comment]
I'm interested, opened a PR for a design on this above.

**Comment by jonathan-innis** [comment]
cc: @akestner
