### ISSUE TITLE
Machine Disruption Gate

### ISSUE THREAD

**Issue by vikas027** [kubernetes-sigs/karpenter#753]
**Tell us about your request**
We already have a way to terminate the instance after X amount of time. It would be great to have a way of doing the same at a specified time as well. For example, say I want to terminate a node(s) at 2:00 AM UTC to save running costs.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are looking to have the ability to scale down nodes at certain times, with ASGs it is easy using the scheduled actions but since Karpenter is managed outside of an ASG (which is a good thing), we can't automatically scale them down to save costs.

**Are you currently working around this issue?**
I may end up writing a lambda function to do the same but it would be great to have this feature inbuilt

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Solved with https://github.com/kubernetes-sigs/karpenter/pull/849

**Comment by bbodenmiller** [comment]
@njtran how can this be achieved now? Specifically looking to block nodes from by disrupted due to expiration or drift during business hours. Disruption due to emptiness is desired anytime however.

**Comment by njtran** [comment]
This should be included in the next release. It sounds like https://github.com/kubernetes-sigs/karpenter/pull/936 is what you're interested in tracking

**Comment by igor-nikiforov** [comment]
> We are looking to have the ability to scale down nodes at certain times, with ASGs it is easy using the scheduled actions but since Karpenter is managed outside of an ASG (which is a good thing), we can't automatically scale them down to save costs.

I'm a bit confused so how this could be achieved with latest version of Karpenter?

Looking at doc I don't see any way to scale down NodePool completely during off hours which is original request about.

**Comment by ronberna** [comment]
I don't think you can achieve that with this latest version of Karpenter.  As a workaround we've had to patch the nodepool to change the cpu limit to 0 to prevent new Karpenter nodes from scaling up and then use a function to delete the existing nodes that Karpenter provisioned before we patched the cpu limit.  It would be great if Karpenter handled this for you or provided a way to scale down based on a parameter or schedule.

**Comment by Bryce-Soghigian** [comment]
> I don't see any way to scale down NodePool completely during off hours which is original request about.

You could try having a cron job that applies the nodepool when you need scale up and removes it when you need scale down?  If you have clear windows of schedules when you want the scaling to start and when to remove all the nodes that should be achievable. 

Deleting the nodepool deletes all subsequent nodeclaims && nodes and effectively does what you need. 


Another more involved consideration we have chatted about following a pattern similar to the deployment-> pod pattern. 

You could provision static instances in a nodepool, or you can set it to auto. Then you simply would have a cron job set that count to 0 during off hours and "auto" during business hours. 

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: general-purpose
spec:
  nodes: 0 | "count"  or "auto"
```  


There are some complications to this model that would need to be designed further though in regards to picking the instances during scale up, or even choosing which instances to scale down in a static model.

**Comment by ronberna** [comment]
Removing and reapplying the nodepool is not an option for us as our nodepools get deployed via a pipeline to a controlled environment so we would have to re-run the pipeline every time we want to scale up to reapply the nodepool.  In some environments, something like this would require a change request.
My thinking on this is there should be a flag in Karpenter to have it scale down (cordon, drain, delete) nodes previously provisioned and not provision any new nodes like it does when the cpu limit in the nodepool is set to 0.  Behavior similar to an ASG where I can just set my min/max/desired to 0 and it scales everything down.  The nodes: 0 "count" or "auto" is an interesting concept, although still trying to wrap my head around how this would actually work.

**Comment by njtran** [comment]
Am I misunderstanding the ask? Sounds like you can block disruption completely with NodePool.Disruption.Budgets 
https://karpenter.sh/docs/concepts/disruption/#disruption-budgets. If you don't think this is properly configurable through disruption budgets, please cut another issue, rather than commenting on a closed issue so that we can track this better.

Specifically on the ask of "scaling down a specific number of nodes with a period of time", Karpenter will scale up and scale down nodes according to your workloads. If you want to scale down your nodes, you'll need to first scale down your workloads to 0, at which Karpenter will consolidate your instances.

**Comment by Bryce-Soghigian** [comment]
+1 To opening a new issue to explain your usecase. Seems these users want a new feature similar to the lambda function to scale down the nodegroups to 0. 

The original ask for machine disruption gate has been solved already so any new feature requests should go on a new issue.  There are many ways in k8s to scale down the nodes either delete them all via k delete with a cron job  paired with a disruption budget or have a cron job scale down all the deployments then karpenter will naturally delete all of the nodes. 


Regardless @AnhQKatalon  or @ronberna  please create a new issue rather than discussing on a closed issue :)

**Comment by ronberna** [comment]
I went ahead and opened a new issue [here](https://github.com/kubernetes-sigs/karpenter/issues/1177)
