### ISSUE TITLE
Respect do-not-disrupt annotation for static pods

### ISSUE THREAD

**Issue by Devern** [kubernetes-sigs/karpenter#863]
### Description

**What problem are you trying to solve?**

Presently, the `karpenter.sh/do-not-disrupt: "true"` annotation will prevent consolidation when present on K8s resources, with the exception of terminating pods, terminal pods, DaemonSet pods and static pods.

For the use case of Airflow on Kubernetes, jobs are spawned as static pods and consolidation causes them to receive sigterm from being evicted. In this use case, it is desirable to exempt these pods from consolidation-initiated eviction.

To that end, this feature request is to implement support for the annotation `karpenter.sh/do-not-disrupt: "true"` on static pods.

**How important is this feature to you?**

Workarounds exist (disabling consolidation, scheduling to a nodegroup without consolidation), however given the transient nature of Airflow workloads, it is desirable to have it execute alongside other workloads, and making full use of consolidation is an enormous boon to efficiency.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Looks potentially related to a fix that was proposed here: #789

**Comment by jonathan-innis** [comment]
@Devern Do y'all use an EKS control plane? As I was going through this, I ran into this issue which I wasn't expecting to hit: https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/351. I'm wondering if this blocks you as well.

**Comment by Devern** [comment]
@jonathan-innis we are using EKS, but not Security Groups for Pods, so it's unclear to me whether this issue would impact us

**Comment by jonathan-innis** [comment]
> we are using EKS, but not Security Groups for Pods

Have you tried it? I'm curious mainly because I believe the vpc-resource-controller is running on the EKS control-plane, so I would expect this `mutatingwebhookconfiguration` to affect you, unless you explicitly disabled it on your cluster.

**Comment by noxjonas** [comment]
not sure if I should create a separate issue, but I think it's related and https://github.com/kubernetes-sigs/karpenter/pull/789 did not address it.

I only have vague details since I'm unable to reliably reproduce the issue, but I'm running hundreds or thousands of static pods everyday and observing a significant amount of them still getting evicted from nodes deprovisioned by consolidation.

So nodes with static pods with the above annotation are not deprovisioned by expiration/consolidation, I can confirm that from karpenter events. But looking at logs of those rare instances where karpenter still evicts static pods, I see this in karpenter logs:
```
disrupting via consolidation delete, terminating 1 nodes (0 pods) <node-x>
```
Which is interesting since events for that pod clearly indicate that it was already scheduled on node-x, but is still pulling the image. Meanwhile karpenter has already started deleting the node, and then evicts the static pod.

is this some timing issue? Or perhaps related to how the pod is checked to be static? I see that [IsOwnedByNode](https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/utils/pod/scheduling.go#L151) function is used to check if pod is a static one, but I can find no documentation about static pods having such an owner reference, and see no such owner references on my cluster

I'm on EKS 1.29 and karpenter 0.35.4

**Comment by jmdeal** [comment]
[Karpenter v0.36.1](https://github.com/kubernetes-sigs/karpenter/releases/tag/v0.36.1) included a fix to mitigate a race condition which could lead to do-not-disrupt pods being disrupted by consolidation. Given the log you provided indicates Karpenter believed 0 pods were scheduled to the node, I suspect this is what you are running into. Are you able to try upgrading and see if that resolves your issue?
